/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient.management.system;

import patient.management.system.function.CalendarWindow;
import patient.management.system.function.AppointmentApproved;
import patient.management.system.function.ConsultationHistory;
import patient.management.system.function.CreateAppointment;
import patient.management.system.function.FinishAppointment;
import patient.management.system.function.FinishConsultation;
import patient.management.system.function.MedicineStock;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.*;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author James Man
 */
public class ConsultationScreen extends javax.swing.JFrame implements PropertyChangeListener {
    
    private SimpleDateFormat sdf = new SimpleDateFormat("d/M/y");
    private DefaultTableModel model;
    private Reader stock_reader;
    private String doctor_name;
    private CalendarWindow next = new CalendarWindow("next");
    private int appointment_no;
    private String user_id;


    /**
     * Creates new form ConsultationScreen
     * @param patient_name
     * @param user_id
     * @param age
     * @param sex
     * @param date
     * @param doctor_name
     * @param appointment_no
     */
    public ConsultationScreen(String patient_name, String user_id, String age, String sex, String date, String doctor_name, int appointment_no) throws IOException {
        initComponents();
        
        this.setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage("src/icon/icons8_hospital_3_30px.png");
        this.setIconImage(icon);
        Medicine_dosage_table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 20));
        Patient_name_label.setText(patient_name);
        Date_label.setText(date);
        Sex_label.setText(sex);
        Age_label.setText(age);
        User_id_label.setText(user_id);
        Appointment_user_id_label.setText(user_id);
        Appointment_patient_name_label.setText(patient_name);
        Appointment_doctor_name_label.setText(doctor_name);
        Next_appointment_date_text.setText(sdf.format(new Date()));

        model = (DefaultTableModel) Medicine_dosage_table.getModel();

        Gson gson = new GsonBuilder().create();

        Reader account_reader = Files.newBufferedReader(Paths.get("src//data//medicine_stock.json"));
        java.lang.reflect.Type medicine_listType = new TypeToken<ArrayList<MedicineStock>>() {
        }.getType();
        ArrayList<MedicineStock> medicines = gson.fromJson(account_reader, medicine_listType);

        for (MedicineStock m : medicines) {
            if (m.getQuantity() > 0) {
                Medicine_combobox.addItem(m.getMedicine_name());
            }
        }
        
        Medicine_dosage_table.getColumnModel().getColumn(0).setPreferredWidth(10);
        Medicine_dosage_table.getColumnModel().getColumn(1).setPreferredWidth(5);
        Medicine_dosage_table.getColumnModel().getColumn(2).setPreferredWidth(200);
        next.addPropertyChangeListener(this);
        this.appointment_no = appointment_no;
        this.user_id = user_id;
        this.doctor_name = doctor_name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Consultation_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Patient_name_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Sex_label = new javax.swing.JLabel();
        Age_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        User_id_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Disease_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Notes_text = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        Medicine_combobox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Quantity_spinner = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dosage_text = new javax.swing.JTextArea();
        Add_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Medicine_dosage_table = new javax.swing.JTable();
        Cancel_button = new javax.swing.JButton();
        Finish_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Date_label = new javax.swing.JLabel();
        Remove_button = new javax.swing.JButton();
        Appointment_panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Create_button = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Appointment_user_id_label = new javax.swing.JLabel();
        Appointment_patient_name_label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Next_appointment_date_text = new javax.swing.JFormattedTextField();
        Appointment_doctor_name_label = new javax.swing.JLabel();
        Skip_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultation");
        setMaximumSize(new java.awt.Dimension(1075, 811));
        setMinimumSize(new java.awt.Dimension(1075, 811));
        setUndecorated(true);

        jPanel2.setMaximumSize(new java.awt.Dimension(1075, 811));
        jPanel2.setPreferredSize(new java.awt.Dimension(1075, 811));
        jPanel2.setLayout(new java.awt.CardLayout());

        Consultation_panel.setBackground(new java.awt.Color(255, 255, 255));
        Consultation_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Consultation_panel.setMaximumSize(new java.awt.Dimension(1075, 811));
        Consultation_panel.setMinimumSize(new java.awt.Dimension(1075, 811));
        Consultation_panel.setPreferredSize(new java.awt.Dimension(1075, 811));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Consultation");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Patient Name");
        jLabel2.setToolTipText("");

        Patient_name_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Patient_name_label.setForeground(new java.awt.Color(102, 102, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sex");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Age");

        Sex_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Sex_label.setForeground(new java.awt.Color(102, 102, 255));

        Age_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Age_label.setForeground(new java.awt.Color(102, 102, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("User ID");

        User_id_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        User_id_label.setForeground(new java.awt.Color(102, 102, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Disease");
        jLabel5.setToolTipText("");

        Disease_text.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Notes");

        Notes_text.setColumns(20);
        Notes_text.setRows(5);
        jScrollPane1.setViewportView(Notes_text);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Medicine");

        Medicine_combobox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Medicine_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Quantity");

        Quantity_spinner.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Dosage");

        Dosage_text.setColumns(20);
        Dosage_text.setRows(5);
        jScrollPane2.setViewportView(Dosage_text);

        Add_button.setBackground(new java.awt.Color(102, 102, 255));
        Add_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Add_button.setForeground(new java.awt.Color(255, 255, 255));
        Add_button.setText("ADD");
        Add_button.setBorderPainted(false);
        Add_button.setFocusPainted(false);
        Add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_buttonActionPerformed(evt);
            }
        });

        Medicine_dosage_table.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Medicine_dosage_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Quantity", "Dosage"
            }
        ));
        Medicine_dosage_table.setToolTipText("");
        Medicine_dosage_table.setRowHeight(25);
        jScrollPane3.setViewportView(Medicine_dosage_table);

        Cancel_button.setBackground(new java.awt.Color(255, 102, 102));
        Cancel_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Cancel_button.setForeground(new java.awt.Color(255, 255, 255));
        Cancel_button.setText("Cancel");
        Cancel_button.setBorderPainted(false);
        Cancel_button.setFocusable(false);
        Cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_buttonActionPerformed(evt);
            }
        });

        Finish_button.setBackground(new java.awt.Color(102, 102, 255));
        Finish_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Finish_button.setForeground(new java.awt.Color(255, 255, 255));
        Finish_button.setText("Finish");
        Finish_button.setBorderPainted(false);
        Finish_button.setFocusPainted(false);
        Finish_button.setFocusable(false);
        Finish_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finish_buttonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Date");

        Date_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Date_label.setForeground(new java.awt.Color(102, 102, 255));

        Remove_button.setBackground(new java.awt.Color(255, 102, 102));
        Remove_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Remove_button.setForeground(new java.awt.Color(255, 255, 255));
        Remove_button.setText("REMOVE");
        Remove_button.setBorderPainted(false);
        Remove_button.setFocusPainted(false);
        Remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Consultation_panelLayout = new javax.swing.GroupLayout(Consultation_panel);
        Consultation_panel.setLayout(Consultation_panelLayout);
        Consultation_panelLayout.setHorizontalGroup(
            Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Consultation_panelLayout.createSequentialGroup()
                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Consultation_panelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(Cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(Finish_button, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Consultation_panelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Consultation_panelLayout.createSequentialGroup()
                                .addGap(420, 420, 420)
                                .addComponent(jLabel1))
                            .addGroup(Consultation_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(Consultation_panelLayout.createSequentialGroup()
                                            .addComponent(Patient_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(Sex_label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Consultation_panelLayout.createSequentialGroup()
                                            .addComponent(Disease_text, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Remove_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Consultation_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(Age_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(User_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consultation_panelLayout.createSequentialGroup()
                                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Consultation_panelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Medicine_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel9)
                                        .addGap(28, 28, 28)
                                        .addComponent(Quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Consultation_panelLayout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(Add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Consultation_panelLayout.setVerticalGroup(
            Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Consultation_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(User_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(Patient_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sex_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Age_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Consultation_panelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Disease_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(Date_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Consultation_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consultation_panelLayout.createSequentialGroup()
                        .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Consultation_panelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Medicine_combobox, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Consultation_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consultation_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Remove_button, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                    .addGroup(Consultation_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Consultation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(Finish_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(Consultation_panel, "card2");

        Appointment_panel.setBackground(new java.awt.Color(255, 255, 255));
        Appointment_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Appointment_panel.setMaximumSize(new java.awt.Dimension(1075, 811));
        Appointment_panel.setMinimumSize(new java.awt.Dimension(1075, 811));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Next Appointment");

        Create_button.setBackground(new java.awt.Color(102, 102, 255));
        Create_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Create_button.setForeground(new java.awt.Color(255, 255, 255));
        Create_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_calendar_30px.png"))); // NOI18N
        Create_button.setText("Create");
        Create_button.setBorderPainted(false);
        Create_button.setFocusable(false);
        Create_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_buttonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("User ID");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Patient Name");

        Appointment_user_id_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        Appointment_patient_name_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("Date");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Doctor Name");

        Next_appointment_date_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        Next_appointment_date_text.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Next_appointment_date_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Next_appointment_date_textMouseClicked(evt);
            }
        });

        Appointment_doctor_name_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        Skip_Button.setBackground(new java.awt.Color(102, 102, 255));
        Skip_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Skip_Button.setForeground(new java.awt.Color(255, 255, 255));
        Skip_Button.setText("Skip");
        Skip_Button.setBorderPainted(false);
        Skip_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skip_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Appointment_panelLayout = new javax.swing.GroupLayout(Appointment_panel);
        Appointment_panel.setLayout(Appointment_panelLayout);
        Appointment_panelLayout.setHorizontalGroup(
            Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Appointment_panelLayout.createSequentialGroup()
                .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Appointment_panelLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Appointment_user_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Appointment_panelLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Appointment_patient_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Next_appointment_date_text, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(Appointment_doctor_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Appointment_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Appointment_panelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(380, 380, 380))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Appointment_panelLayout.createSequentialGroup()
                        .addComponent(Skip_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(Create_button, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))))
        );
        Appointment_panelLayout.setVerticalGroup(
            Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Appointment_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Appointment_user_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Appointment_patient_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Next_appointment_date_text, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(Appointment_doctor_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(122, 122, 122)
                .addGroup(Appointment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Skip_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Create_button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jPanel2.add(Appointment_panel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Cancel_buttonActionPerformed

    private void Add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_buttonActionPerformed
        // TODO add your handling code here:
        int qty = (Integer) Quantity_spinner.getValue();
        
        if (qty > 0 && !Dosage_text.getText().isEmpty() && Medicine_combobox.getSelectedIndex() != 0) {

            Gson gson = new GsonBuilder().create();

            try {
                stock_reader = Files.newBufferedReader(Paths.get("src//data//medicine_stock.json"));
            } catch (IOException ex) {
                Logger.getLogger(ConsultationScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            java.lang.reflect.Type stock_listType = new TypeToken<ArrayList<MedicineStock>>() {
            }.getType();
            ArrayList<MedicineStock> stocks = gson.fromJson(stock_reader, stock_listType);
            
            for (MedicineStock s : stocks) {
                if (s.getMedicine_name().equals(Medicine_combobox.getSelectedItem().toString())) {
                    if (s.getQuantity() < 10) {
                        JOptionPane.showMessageDialog(null, "The remain stock is less than 10.", "REMINDER", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        model.addRow(new Object[]{Medicine_combobox.getSelectedItem().toString(), qty, Dosage_text.getText()});
                        Quantity_spinner.setValue(0);
                        Medicine_combobox.setSelectedIndex(0);
                        Dosage_text.setText("");
                    }
                }
            }
        }

    }//GEN-LAST:event_Add_buttonActionPerformed

    private void Remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_buttonActionPerformed
        // TODO add your handling code here:
        if(Medicine_dosage_table.getSelectedRowCount() == 1) {
            model.removeRow(Medicine_dosage_table.getSelectedRow());
        } else if(Medicine_dosage_table.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a account before delete!", "WARNING!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Remove_buttonActionPerformed

    private void Finish_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finish_buttonActionPerformed
        // TODO add your handling code here:
        int rows = Medicine_dosage_table.getRowCount();
        if (!Disease_text.getText().isEmpty() && rows > 0) {
            String disease = Disease_text.getText();
            String patient_name = Patient_name_label.getText();
            String userid = User_id_label.getText();
            String notes = Notes_text.getText();
            String medicines = "";
            String quantity = "";
            String dosage = "";
            
            for (int i = 0; i < rows; i++) {
                if (i + 1 < rows) {
                    medicines += Medicine_dosage_table.getValueAt(i, 0) + ",";
                    quantity += Medicine_dosage_table.getValueAt(i, 1) + ",";
                    dosage += Medicine_dosage_table.getValueAt(i, 2) + ",";
                } else {
                    medicines += Medicine_dosage_table.getValueAt(i, 0);
                    quantity += Medicine_dosage_table.getValueAt(i, 1);
                    dosage += Medicine_dosage_table.getValueAt(i, 2);
                }
            }
            
            try {
                Date date = new SimpleDateFormat("dd/MM/yyyy").parse(Date_label.getText());           
                ConsultationHistory history = new ConsultationHistory(date, disease, doctor_name, patient_name, userid, medicines, quantity, dosage, notes, 0, false);
                new FinishConsultation().AddHistory(history);
                
                Consultation_panel.setVisible(false);
                Appointment_panel.setVisible(true);
            } catch (NoSuchAlgorithmException | IOException | ParseException ex) {
                Logger.getLogger(ConsultationScreen.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_Finish_buttonActionPerformed

    private void Skip_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skip_ButtonActionPerformed
        // TODO add your handling code here:
        try {
            new FinishAppointment().FinishAppointment(appointment_no);
        } catch (NoSuchAlgorithmException | IOException ex) {
            Logger.getLogger(ConsultationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_Skip_ButtonActionPerformed

    private void Next_appointment_date_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next_appointment_date_textMouseClicked
        // TODO add your handling code here:
        next.setLocation(Next_appointment_date_text.getLocationOnScreen().x, (Next_appointment_date_text.getLocationOnScreen().y + Next_appointment_date_text.getHeight()));
        //get the Date and assign it to the calendar
        Date d = new Date();

        next.resetSelection(d);
        next.setUndecorated(true);
        next.setVisible(true);
    }//GEN-LAST:event_Next_appointment_date_textMouseClicked

    private void Create_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_buttonActionPerformed
        try {
            // TODO add your handling code here:
            new FinishAppointment().FinishAppointment(appointment_no);
            
            Date appointment_date = new SimpleDateFormat("dd/MM/yyyy").parse(Next_appointment_date_text.getText()); 
            AppointmentApproved approved_approvement = new AppointmentApproved(0, user_id, doctor_name, appointment_date, new Date(), false);
            new CreateAppointment().CreateFormalAppointment(approved_approvement);
        } catch (NoSuchAlgorithmException | IOException | ParseException ex) {
            Logger.getLogger(ConsultationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Create_buttonActionPerformed
    
    @Override
    public void propertyChange(PropertyChangeEvent event) {

        //get the selected date from the calendar control and set it to the text field
        if (event.getPropertyName().equals("next_selectedDate")) {

            java.util.Calendar cal = (java.util.Calendar) event.getNewValue();
            Date next_selDate = cal.getTime();
            Next_appointment_date_text.setValue(next_selDate);
        }
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConsultationScreen("","","","","","",0).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ConsultationScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_button;
    private javax.swing.JLabel Age_label;
    private javax.swing.JLabel Appointment_doctor_name_label;
    private javax.swing.JPanel Appointment_panel;
    private javax.swing.JLabel Appointment_patient_name_label;
    private javax.swing.JLabel Appointment_user_id_label;
    private javax.swing.JButton Cancel_button;
    private javax.swing.JPanel Consultation_panel;
    private javax.swing.JButton Create_button;
    private javax.swing.JLabel Date_label;
    private javax.swing.JTextField Disease_text;
    private javax.swing.JTextArea Dosage_text;
    private javax.swing.JButton Finish_button;
    private javax.swing.JComboBox<String> Medicine_combobox;
    private javax.swing.JTable Medicine_dosage_table;
    private javax.swing.JFormattedTextField Next_appointment_date_text;
    private javax.swing.JTextArea Notes_text;
    private javax.swing.JLabel Patient_name_label;
    private javax.swing.JSpinner Quantity_spinner;
    private javax.swing.JButton Remove_button;
    private javax.swing.JLabel Sex_label;
    private javax.swing.JButton Skip_Button;
    private javax.swing.JLabel User_id_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
